import { formatSize } from '@src/utils';

export const Spacing0 = formatSize(0);
export const Spacing1 = formatSize(1);
export const Spacing2 = formatSize(2);
export const Spacing3 = formatSize(3);
export const Spacing4 = formatSize(4);
export const Spacing6 = formatSize(6);
export const Spacing5 = formatSize(5);
export const Spacing8 = formatSize(8);
export const Spacing10 = formatSize(10);
export const Spacing12 = formatSize(12);
export const Spacing14 = formatSize(14);
export const Spacing15 = formatSize(15);
export const Spacing16 = formatSize(16);
export const Spacing20 = formatSize(20);
export const Spacing24 = formatSize(24);
export const Spacing30 = formatSize(30);
export const Spacing32 = formatSize(32);
export const Spacing48 = formatSize(48);
export const Spacing50 = formatSize(50);
export const Spacing58 = formatSize(58);
export const Spacing64 = formatSize(64);
export const Spacing77 = formatSize(77);
export const Spacing90 = formatSize(90);
